Video listing page
Arpit-dotcom/Video-Library pull request #3
Opened 2022-04-22 18:39 UTC by Arpit-dotcom

Description-

- videoListing page should be added
- contains a api data
- add components navbar, main, footer
- add filtered part

File to check-

- src/contexts/video-listing.jsx
- src/pages/video-listing/main.jsx
- src/reducer/video-listing.jsx
- src/utils/video-listing.jsx

Preview-

https://user-images.githubusercontent.com/86866251/164774410-d7a86336-dd95-41f8-86e8-8d3e7b4be632.mp4

2022-04-22 19:33 UTC, govardhanreddyc79 commented
Clean and readable code.
Good folder structure

2022-04-22 20:13 UTC, shmbajaj requested changes

2022-04-22 20:13 UTC, shmbajaj commented on src/pages/video-listing/main.jsx
> +                style={{ cursor: "pointer" }}
This can be done in css files imported.

2022-04-22 20:13 UTC, shmbajaj commented on src/pages/video-listing/video-listing.jsx
> +    getVideoListing(category, videoDispatch);
This line of code works?

2022-04-22 20:13 UTC, shmbajaj commented on src/utils/video-listing.jsx
> +export const getFilteredVideos = ([...videos], state) => {
Argument named state, has different descriptive meaning than for what being used here.

2022-04-23 05:01 UTC, Arpit-dotcom commented on src/pages/video-listing/video-listing.jsx
> +    getVideoListing(category, videoDispatch);
yaah works for home category

2022-04-23 05:12 UTC, merged